"""add youtube download tracking

Revision ID: 00cbfdcc7e95
Revises: 802b380b4115
Create Date: 2026-08-17 23:36:34.755351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '00cbfdcc7e95'
down_revision: Union[str, None] = '802b380b4115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtubevideo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_attempted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('download_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtubevideo', schema=None) as batch_op:
        batch_op.drop_column('download_error')
        batch_op.drop_column('download_attempted_at')

    # ### end Alembic commands ###
