"""add oauth reconnect tracking

Revision ID: 802b380b4115
Revises: a87d0c51c87d
Create Date: 2026-08-17 21:16:32.099997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '802b380b4115'
down_revision: Union[str, None] = 'a87d0c51c87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauthaccount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_reconnect', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauthaccount', schema=None) as batch_op:
        batch_op.drop_column('last_error')
        batch_op.drop_column('needs_reconnect')

    # ### end Alembic commands ###
