"""initial schema

Revision ID: a87d0c51c87d
Revises: 
Create Date: 2026-08-17 20:34:02.793153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'a87d0c51c87d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauthaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'tiktok', name='oauthprovider'), nullable=False),
    sa.Column('external_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('granted_scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauthaccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauthaccount_external_account_id'), ['external_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauthaccount_provider'), ['provider'], unique=False)

    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_times', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('youtubevideo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('youtube_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privacy_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detected_as_short', sa.Boolean(), nullable=False),
    sa.Column('detection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_override', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('youtubevideo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtubevideo_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_youtubevideo_youtube_video_id'), ['youtube_video_id'], unique=True)

    op.create_table('mediaasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sa.Enum('local_file', 'import_archive', 'youtube_source', name='mediasource'), nullable=False),
    sa.Column('youtube_video_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('video_codec', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_codec', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filesize_bytes', sa.Integer(), nullable=True),
    sa.Column('processed_local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_confirmed', sa.Boolean(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['youtube_video_id'], ['youtubevideo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mediaasset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mediaasset_sha256'), ['sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_mediaasset_youtube_video_id'), ['youtube_video_id'], unique=False)

    op.create_table('tiktokvideo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_account_id', sa.Integer(), nullable=False),
    sa.Column('tiktok_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tiktok_created_at', sa.DateTime(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['oauth_account_id'], ['oauthaccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tiktokvideo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tiktokvideo_oauth_account_id'), ['oauth_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tiktokvideo_tiktok_video_id'), ['tiktok_video_id'], unique=True)

    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oauth_account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'ready', 'scheduled', 'uploading', 'processing', 'draft', 'published', 'failed', 'cancelled', name='publicationstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('external_publish_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tiktok_caption', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['mediaasset.id'], ),
    sa.ForeignKeyConstraint(['oauth_account_id'], ['oauthaccount.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id', 'oauth_account_id', name='uq_publication_asset_account')
    )
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_oauth_account_id'), ['oauth_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_status'), ['status'], unique=False)

    op.create_table('auditevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_publication_id', sa.Integer(), nullable=True),
    sa.Column('related_media_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_media_asset_id'], ['mediaasset.id'], ),
    sa.ForeignKeyConstraint(['related_publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditevent_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_event_type'), ['event_type'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('youtube_sync', 'tiktok_publish', 'tiktok_status_poll', 'tiktok_sync', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='jobstatus'), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_publication_id'), ['publication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_status'))
        batch_op.drop_index(batch_op.f('ix_job_publication_id'))
        batch_op.drop_index(batch_op.f('ix_job_job_type'))

    op.drop_table('job')
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditevent_event_type'))
        batch_op.drop_index(batch_op.f('ix_auditevent_created_at'))

    op.drop_table('auditevent')
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_status'))
        batch_op.drop_index(batch_op.f('ix_publication_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_publication_provider'))
        batch_op.drop_index(batch_op.f('ix_publication_oauth_account_id'))
        batch_op.drop_index(batch_op.f('ix_publication_media_asset_id'))

    op.drop_table('publication')
    with op.batch_alter_table('tiktokvideo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tiktokvideo_tiktok_video_id'))
        batch_op.drop_index(batch_op.f('ix_tiktokvideo_oauth_account_id'))

    op.drop_table('tiktokvideo')
    with op.batch_alter_table('mediaasset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mediaasset_youtube_video_id'))
        batch_op.drop_index(batch_op.f('ix_mediaasset_sha256'))

    op.drop_table('mediaasset')
    with op.batch_alter_table('youtubevideo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtubevideo_youtube_video_id'))
        batch_op.drop_index(batch_op.f('ix_youtubevideo_channel_id'))

    op.drop_table('youtubevideo')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('schedule')
    with op.batch_alter_table('oauthaccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauthaccount_provider'))
        batch_op.drop_index(batch_op.f('ix_oauthaccount_external_account_id'))

    op.drop_table('oauthaccount')
    # ### end Alembic commands ###
